config/routes.rb
Rails.application.routes.draw do
 
  
 devise_for :users
 mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
 get '/errorview/error_page'
 
 root 'posts#show'
 
 # posts
 get '/posts/new' => 'posts#new'
 post '/posts/create' => 'posts#create'
 get '/posts/show' => 'posts#show'
 get '/posts/detail/:post_id' => 'posts#detail'
 get '/posts/destroy/:post_id' => 'posts#destroy'
 get '/posts/edit/:post_id' => 'posts#edit'
 post '/posts/update/:post_id' => 'posts#update'
 
 # comments
 post '/posts/detail/:post_id/comments/create' => 'comments#create'
 post '/posts/detail/:post_id/comments/destroy/:comment_id' => 'comments#destroy'
 
 # likes
 post '/:post_id/like_create' => 'likes#like_create'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :Post
end

app/models/like.rb
class Like < ActiveRecord::Base
    belongs_to :Post
end

app/models/post.rb
class Post < ActiveRecord::Base
    resourcify
    include Authority::Abilities
    
    has_many :comments
    has_many :likes
    
    validates :title, presence: {message: "제목이 작성되지 않았습니다."}, length: {minimum: 2}
    validates :content, presence: {message: "내용이 작성되지 않았습니다."}
    

    belongs_to :user
    
    validates :title,           
                presence: true    
    validates :content,            
                presence: true
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true
            # :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  include Authority::UserAbilities
  has_many :posts

  after_create :assign_default_role, if: Proc.new { User.count > 1 } 
   private
   def assign_default_role
       add_role :user
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    
    def create
        @comment = Comment.new
        @comment.content = params[:comment_content]
        @comment.post_id = params[:post_id]
        @comment.save
        
        redirect_to "/posts/detail/#{params[:post_id]}"
    end
    
    def destroy
        @comment = Comment.find(params[:comment_id])
        @comment.destroy
        
        redirect_to "/posts/detail/#{params[:post_id]}"
    end
    
    def edit
        @comment = Comment.find(params[:comment_id])
    end
    
    def update
        @comment = Comment.find(params[:comment_id])
        @comment.content = params[:comment_content]
        @comment.post_id = params[:post_id]
        @comment.save
        
        redirect_to :back
    end
end

app/controllers/errorview_controller.rb
class ErrorviewController < ApplicationController
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
     def like_create
        like = Post.find(params[:post_id]).likes.create(likeCount: params[:likeCount])
        like.save
        redirect_to :back
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_filter :authenticate_user!
    def new
        # 사용자가 데이터를 입력할 화면
        #자동으로 액션 이릅과 같은 화면을 불러서 보여줘라 
    end
    
    def create
        # 입력받은 데이터를 실제 DB에 저장할 액션
        # 새로운 화면이 필요없음, 저장만 하면됨 
        
        @post = Post.new
        @post.userName = params[:userId]
        @post.content = params[:content]
        @post.title = params[:title]
        
        file = params[:pic]
        uploader = AvatarUploader.new
        uploader.store!(file)
        
        @post.image_url =uploader.url
        @post.save
        redirect_to '/posts/show'
    end
    
    def show
        @posts = Post.all.reverse
    end
    
    def destroy
        # authorize_action_for @post
        @post = Post.find(params[:post_id])
        @post.destroy
        redirect_to '/'
    end
    
    def detail
        @one_post = Post.find(params[:post_id])
        @comments = Comment.where(:post_id => params[:post_id])
        @likes = Like.first
    end 
    
    def edit
        # authorize_action_for @post
        @post = Post.find(params[:post_id])
    end
      
    def update
        # authorize_action_for @post
        @post = Post.find(params[:post_id])
        @post.title = params[:title]
        @post.content = params[:content]
        @post.save
        redirect_to '/posts/show'
    end
end

app/controllers/upload_controller.rb
class UploadController < ApplicationController
    def upload
        file = params[:pic]
        uploader = AvatarUploader.new
        uploader.store!(file)
        redirect_to '/'
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/errorview_helper.rb
module ErrorviewHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/upload_helper.rb
module UploadHelper
end

app/views/errorview/error_page.html.erb
<div class="col-md-12">
    <h1>Access Denied!</h1>
    <a href="/posts">main</a><br>
    <%= link_to 'main', root_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Team2'SNS</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    
    <!-- Bootstrap CDN -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    
    <!--허은실-->
    <style type="text/css"> div { cursor: url(/assets/Hello_Normal.cur), auto; }</style>
  </head>

  <body>
    <!--허은실-->
    <script type="text/javascript">
    	$('#MyCanvas').css({'/assets/Hello_Normal':'url(Hello_Normal.cur), auto'});
    </script>
    <div id="MyCanvas">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/detail.html.erb
<style>
    .card-cls{
        padding : 100pt;
    }
    .like{
        float:right;
    }
    .delete-btn{
        float:right;
    }
</style>

<head>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
    <div class="card-cls">
        <div class="card">
            
            <div class="card-block">
                <h4 class="card-title"><%= @one_post.title%></h4>
                <h6 class="card-subtitle mb-2 text-muted"><%= @one_post.userName %></h6>
                <p class="card-text"><%= @one_post.content %></p>
                <!--<img src="<%= @one_post.image_url%>" style="height:400px; width:300px" >-->
                <img src="<%= image_path @one_post.image_url %>"  style="height:400px; width:300px" >
                <!-- 좋아요 -->
                <form action="/<%= @one_post.id %>/like_create" method="post" style="float:right;">
                    <button type="submit" class="btn btn-outline-danger"><%= Post.find(@one_post.id).likes.count %>
                    <i class="fa fa-heart" aria-hidden="true"></i> </button>
                </form>
                <br>
                <hr>
                
                <!--댓글 구현-->
                <p><b>댓글</b></p>
                <div class="comment_div">
                    <% @comments.each do |c| %>
                        <p><%= c.content %>
                        <a href="/posts/detail/<%= @one_post.id %>/comments/destroy/<%= c.id %>" data-method="post" class="delete-btn">삭제</a>
                        <br>
                        </p>
                    <% end %>
                </div>
                
            </div>
            
            <!-- 댓글 입력 -->
            <div class="col-lg-11">
                <div class="input-group">
                  <input type="text" class="form-control" name="comment_content" id="id_comment" placeholder="">
                  <span class="input-group-btn">
                    <button class="btn btn-secondary" id="comment_submit" type="submit" style="width: 50px;">입력</button>
                  </span>
                </div>
            </div>
            <br>
        </div>
        <a href="/posts/show" class="card-link" style="float:right;">처음으로 돌아가기</a>
    </div>
</body>

<script>
    $(function(){
        $('#comment_submit').click(function(){
            var comment_content = $('#id_comment').val();
            // alert(comment_content);
           $.ajax({
              method: "POST",
              url: '/posts/detail/<%= @one_post.id %>/comments/create',
              data: { comment_content: comment_content, post_id: <%= @one_post.id %> },
              success: function(){
                  alert('댓글이 달리지 않았습니다.');
              },
              error: function(){
                //   alert('성공');
                  $('.comment_div').append(comment_content);
                  $('#id_comment').val('');
              }
            })
        });
    });
</script>

app/views/posts/edit.html.erb
<link rel="stylesheet" href="/assets/home.scss">

<%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
  <header>Login</header>
  <div class="form-inputs">
    <%= f.input :email, required: false, autofocus: true %>
    <%= f.input :password, required: false %>
    <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Log in" %>
  </div>
  <div style="margin-left: 20px"><%= render "devise/shared/links" %></div>
<% end %>

app/views/posts/new.html.erb
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>

<style>
    .write-form{
        padding : 40pt;
    }
    span {
            display: none;
        }
</style>

<body>
    <div class="write-form">
        <form action="/posts/create" method="post" enctype="multipart/form-data">
            <div class="form-group">
            <label for="exampleInputEmail1">작성자</label>
            <input type="email" class="form-control" name="userId" id="userId" value="<%= current_user.email %>">
            </div>
            
            <div class="form-group">
            <label for="exampleInputPassword1">제목</label>
            <input type="text" class="form-control" name="title" id="titleId">
            </div>
            
            <!-- 가현 jquery -->
            <div class ="form-group">
            <label for="exampleInputPassword1">내용</label>
            <span>신중하게 작성해주세요!</span>
            <textarea class = "form-control" name="content" id="contentId" rows="3"></textarea> 
            </div>
            <input type="file" name="pic" accept="image/*">
            <center><button type="submit" class="btn btn-default" id="comment_submit">작성하기</button></center>
        </form>
    </div>
</body>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script>
    $(document).ready(function(){
        $("textarea").focus(function(){
            $("span").css("display", "inline").fadeOut(2000);
        });
    });
</script>

app/views/posts/show.html.erb
<style>
    .container{
        padding-top: 20pt;
    }
    .write-board{
        float :right;
    }
    .btn-outline-info {
      color: #5bc0de;
      background-image: none;
      background-color: transparent;
      border-color: #5bc0de;
      float: right;
      margin: 10pt;
    }
    .userInfo{
      /*float: right;*/
      margin-left: 90pt;
      margin-top: 50pt;
    }
</style>


<html>
  <head>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>
  
  <body>
    
    <!-- 이메일, 로그아웃, 정보수정 버튼 만들기 -->
    <div class="userInfo">
      <br>
      <button class="btn_show" style="padding:3px">open</button>
      <div class="form-inline" id="btn_word">
          <% if user_signed_in? %>
            <p style="margin-right:10pt;"><b><%= current_user.email %></b>님, 환영합니다!</p><br>
            <%= button_to "logout", destroy_user_session_path, method: :delete, data: {confirm: "로그아웃 하시겠습니까?"}, :class => "btn btn-secondary btn-sm" %>
            <br>
            <% if current_user.email != 'admin@email.com'%>
              <%= button_to "edit", edit_user_registration_path, method: :get, :class => "btn btn-secondary btn-sm" %>
            <% else %>
              <%= link_to "AdminPage", '/admin', :class => "btn btn-secondary btn-sm" %>
            <% end %>  
          <% end %>
      </div>
      <button class="btn_hide" style="padding:3px">close</button>
    </div>

    
    <div class="container" style ="margin-top:30px;">
      <center><h3 class="hover1">Team2 SNS</h3></center>
      <a href="/posts/new"><button type="button" class="btn btn-outline-info" style="float:left;">글쓰기</button></a>
      <br>
    
      <table class="table table-sm">
          <thead>
            <tr>
              <th>글쓴이</th>
              <th>제목</th>
              <th>날짜<th>
            </tr>
          </thead>
          <tbody>
              <% @posts.each do |p| %>
              <tr>
                <td><%= p.userName %></td>
                <td><a href ="/posts/detail/<%= p.id %>"><%= p.title %></a></td>
                <td><%= p.created_at.in_time_zone("Asia/Seoul").strftime("%Y-%m-%d")%></td>
                <% if current_user.email == p.userName || current_user.email == "admin@email.com" %>
                <td ><a href ="/posts/edit/<%= p.id %>">수정</a> <a href ="/posts/destroy/<%= p.id %>" data-confirm="삭제하시겠습니까?">삭제</a></td>
                <% end %>
              </tr>
              <% end %>
          </tbody>
      </table>
    </div>
  </body>
</html>

<script type="text/javascript" src="http://code.jquery.com/jquery-2.1.0.min.js" ></script>
<script type="text/javascript"></script>
<script>
  // 이림아 스크립트 
  $(function(){
  $('.btn_show').click(function(){
    $('#btn_word').show();
    $('#btn_show').hide();
    
  });
  $('.btn_hide').click(function(){
    $('#btn_word').hide();
    $('.btn_hide').show();
  });
  });
  
  // 구유림 스크립트
  $(function(){
    var hover1 = $('.hover1');
    hover1.hover(function(){
      hover1.css('color','#00cccc');
    },function(){
      hover1.css('color','#66cc00');
    });
  });
  
  
</script>